### ISSUE TITLE
Refactor FrontPageActivity layout to use ConstraintLayout instead of Relative

### ISSUE THREAD

**Issue by Yabdro** [SachaKor/SDP-PolyCrowd#173]
The aim is to have the tests for FrontPageActivity pass on the 3.3  WQVGA API 29 emulator or any other emulator with a similar screen size. Any hard-coded values should be removed to avoid dependence on any specific emulator.

**Comment by choelzl** [comment]
In tests/flows #166 and #167, who are on master, we have tests for the front page activity that pass on those emulators. We don't need to refactor anything. In my opinion this issue is invalid and should be closed.
